In [1]:
import numpy as np  
list1=[[1,2,3,4,5]]
arr=np.array(list1)
print(arr)


[[1 2 3 4 5]]


In [2]:
import numpy as np  # type: ignore
arr=np.array([1,2,3,4,5,6])
print(arr)
type(arr)

[1 2 3 4 5 6]


numpy.ndarray

In [4]:
zero_arr=np.zeros((3,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
ones_arr=np.ones((4,4))
print(ones_arr)
ones_arr.ndim

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


2

In [6]:
ran_arr=np.arange(0,20,1)
print(ran_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [7]:
ran_arra=np.arange(5,16)
print(ran_arra)

[ 5  6  7  8  9 10 11 12 13 14 15]


In [8]:
a=np.full((6,7),6)
a

array([[6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6]])

In [9]:
b=np.full((5,3),7)
b

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [10]:
lins_arr=np.linspace(0,1,9)
print(lins_arr)
lins_arr.ndim

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


1

In [11]:
lins_arr=np.linspace(100,1000,5)
print(lins_arr)
lins_arr.ndim

[ 100.  325.  550.  775. 1000.]


1

In [12]:
iden_arr=np.eye(4)
print(iden_arr)
iden_arr.ndim

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


2

In [13]:
ran_arr=np.random.rand(2,3)
print(ran_arr)

[[0.85290875 0.43230025 0.62743549]
 [0.75246525 0.45119329 0.79183503]]


In [14]:
ran_arran=np.random.rand(4,4)
print(ran_arran)
ran_arran.ndim

[[0.26797733 0.66581062 0.44956248 0.93860463]
 [0.37115102 0.27389989 0.6971324  0.49092987]
 [0.49056542 0.01382536 0.5418031  0.6547208 ]
 [0.13784461 0.69203958 0.69790405 0.04436024]]


2

In [15]:
ran_arran.shape

(4, 4)

In [16]:
ran_arr.shape

(2, 3)

In [17]:
arrr=np.array([[1,3,5],
               [3,5,8],
                [3,5,8]])
print(arrr.shape)
print(arrr.dtype)
print(arrr.size)
print(arrr.ndim)

(3, 3)
int64
9
2


In [18]:
arrr1=np.array([[1,0,5],
               [8,5,8],
                [1,7,8]])
print("Shape of array :",arrr1.shape)
print("DataType of array :",arrr1.dtype)
print("Size of array :",arrr1.size)
print("Dimension of array :",arrr1.ndim)

Shape of array : (3, 3)
DataType of array : int64
Size of array : 9
Dimension of array : 2


In [19]:
a = np.array([[2,5,8,8],[3,6,6,7]])
b = np.array([[9,8,3,8],[3,6,7,8]])
print(a+b)

print(a-b)

print(a*b)

print(a/b)

print(a%b)

a.ndim

[[11 13 11 16]
 [ 6 12 13 15]]
[[-7 -3  5  0]
 [ 0  0 -1 -1]]
[[18 40 24 64]
 [ 9 36 42 56]]
[[0.22222222 0.625      2.66666667 1.        ]
 [1.         1.         0.85714286 0.875     ]]
[[2 5 2 0]
 [0 0 6 7]]


2

In [20]:
a = np.array([2,5,8,8])
b=54
print(a+b)

[56 59 62 62]


In [21]:
a = np.array([[2,5,8,8],[3,6,6,7]])
# c = np.array([[2],[4]])
c = np.array([4,5,6,6])
print(a+c)


[[ 6 10 14 14]
 [ 7 11 12 13]]


In [22]:
c = np.array([4,5,6,6])
print("Squareroot of array :",np.sqrt(c))
print("Sum of array :",np.sum(c))
print("Square of array :",np.power(c,2))

Squareroot of array : [2.         2.23606798 2.44948974 2.44948974]
Sum of array : 21
Square of array : [16 25 36 36]


In [23]:
y = np.array([1,2,3,4])
y_p = np.array([1.1,2.05,3.11,4.02])
y_sub = np.subtract(y,y_p)
total = np.power(y_sub,2)
print(total)
sum_power=np.sum(total)
print(sum_power)


[0.01   0.0025 0.0121 0.0004]
0.024999999999999956


In [24]:
angles=np.array([0,30,50,70,90])
radians=np.deg2rad(angles)
print(radians)
cos=np.cos(radians)
print(cos)
sin=np.sin(radians)
print(sin)
degree=np.rad2deg(radians)
print(degree)

[0.         0.52359878 0.87266463 1.22173048 1.57079633]
[1.00000000e+00 8.66025404e-01 6.42787610e-01 3.42020143e-01
 6.12323400e-17]
[0.         0.5        0.76604444 0.93969262 1.        ]
[ 0. 30. 50. 70. 90.]


In [3]:
d=np.array([0,1,2,3])
radians=np.deg2rad(d)

print(np.exp(d))
print(np.sqrt(d))
print(np.sin(radians))
print(np.log(d))


[ 1.          2.71828183  7.3890561  20.08553692]
[0.         1.         1.41421356 1.73205081]
[0.         0.01745241 0.0348995  0.05233596]
[      -inf 0.         0.69314718 1.09861229]


C:\Users\1212a\AppData\Local\Temp\ipykernel_8496\4283069101.py:7: RuntimeWarning: divide by zero encountered in log
  print(np.log(d))


In [26]:
print(np.sin(d))

[0.         0.84147098 0.90929743 0.14112001]


In [27]:
d=np.array([[0,1,2,3],[5,6,8,9]])
print(np.sum(d))



34


In [28]:
print("Sum of number with respect to row",np.sum(d,axis=0))
print("Sum of number with respect to column",np.sum(d,axis=1))

Sum of number with respect to row [ 5  7 10 12]
Sum of number with respect to column [ 6 28]


In [29]:
print(np.sum(d))
print(np.mean(d))
print(np.max(d))
print(np.min(d))

34
4.25
9
0


In [30]:
d=np.array([0,1,2,3])
x=np.copy(d)
x[0] = 42
print(d)
print(x)

[0 1 2 3]
[42  1  2  3]


In [31]:
d=np.array([0,1,2,3])
x=d.view()
x[0] = 42
print(d)
print(x)

[42  1  2  3]
[42  1  2  3]


In [32]:
d=np.array([0,1,2,3,1,3,1,1,5,1])
x=np.where(d==1)
y = np.searchsorted(d,1)
print(x)
print(y)


(array([1, 4, 6, 7, 9]),)
1


In [33]:
d_2 = np.array([[3,2,1],[2,5,6]])
print(np.sort(d_2))

[[1 2 3]
 [2 5 6]]


In [34]:
d=np.array([0,1,2,3,1,3,1,1,5,1])
print(d[0])

0


In [35]:
d_2 = np.array([[3,2,1],[2,5,6],[7,8,9]])
print(d_2[0:3,0])

[3 2 7]


In [36]:
d_3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
d_3[np.zeros== d_3[1:3,1:3]]
d_3



IndexError: boolean index did not match indexed array along axis 0; size of axis is 4 but size of corresponding boolean axis is 2

In [37]:
import numpy as np
arr = np.array([5,10,15,20,25])
print("Element greater than 5 and less than 20",arr[(arr>5) & (arr<20)])

Element greater than 5 and less than 20 [10 15]


In [38]:
arr = np.array([10,20,30,40,50])
print("Element at indices 1,3 and 4 ", arr[1:5])

Element at indices 1,3 and 4  [20 30 40 50]


In [39]:

arr = np.arange(1,10)
print("Without reshape:",arr)
reshaped_arr = arr.reshape(3,3)
reshaped_arr

Without reshape: [1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
arr = np.arange(1,24,2)
arr.reshape(3,4)

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [111]:
arr = np.arange(0,1,10)

In [112]:
arr = np.arange(1,9)
print(arr)
arr_r = arr.reshape(2,4)
print(arr_r)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [113]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
t = arr.transpose()
t

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [114]:
arr = np.array([[1,2,3],[4,5,6]])
arr1 = np.array([[[1,2,3],[4,5,6]]])
print(arr.ndim)
print(arr1.ndim)
f = arr1.flatten()
f

2
3


array([1, 2, 3, 4, 5, 6])

In [115]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.flatten())

[1 2 3 4 5 6]


In [116]:
arr = np.array([[1,2,3],[4,5,6]])
arr1 = np.array([[8,4,8],[2,6,7]])
result1 = np.concatenate((arr,arr1),axis = 0)
print(result1)
result2 = np.concatenate((arr,arr1),axis = 1)
print(result2)

[[1 2 3]
 [4 5 6]
 [8 4 8]
 [2 6 7]]
[[1 2 3 8 4 8]
 [4 5 6 2 6 7]]


In [117]:
arr = np.array([1,2,3])
arr1 = np.array([4,5,6])
result = np.hstack((arr,arr1))
result2 = np.vstack((arr,arr1))
print(result)
print(result2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [125]:
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.dot(A,B)
print("Dot product of A and B is:",C)

Dot product of A and B is: 32


In [122]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.dot(A,B)
print("Dot product of A and B is:\n",C)

Dot product of A and B is:
 [[19 22]
 [43 50]]


Martices Multiplication

In [127]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = A @ B
D = np.matmul(A,B)
print("Multiplication of A and B is:\n",C)
print("Multiplication of A and B is:\n",D)

Multiplication of A and B is:
 [[19 22]
 [43 50]]
Multiplication of A and B is:
 [[19 22]
 [43 50]]


Inverse of Matrices

In [132]:
A = np.array([[1,2],[3,4]])
A_inv = np.linalg.inv(A)
print("inverse of matrix A is\n" , A_inv)
print("Product A and A_inv is\n", A_inv @ A)

inverse of matrix A is
 [[-2.   1. ]
 [ 1.5 -0.5]]
Product A and A_inv is
 [[1.00000000e+00 0.00000000e+00]
 [2.22044605e-16 1.00000000e+00]]


In [134]:
B = np.array([[5,6],[7,8]])
B_inv = np.linalg.inv(B)
print("inverse of matrix B is\n",B_inv)
print("Product A and A_inv is\n", B @ B_inv)

inverse of matrix B is
 [[-4.   3. ]
 [ 3.5 -2.5]]
Product A and A_inv is
 [[1. 0.]
 [0. 1.]]


Determinants

In [139]:
B = np.array([[5,6],[7,8]])
print("B matix is :\n",B)
det_B = np.linalg.det(B)
print("determinants of matrix B is:\n",det_B)

B matix is :
 [[5 6]
 [7 8]]
determinants of matrix B is:
 -2.000000000000005


EigenValues and EigenVectors

Linear Algebra $x$ and $y$ values

In [142]:
A = np.array([[1,2],[3,4]])
B = np.array([5,6])
result = np.linalg.solve(A,B)
print(result)

[-4.   4.5]


Distributions

In [156]:
random_int = np.random.randint(0,12,size=(2,3))
print(random_int)

[[ 8 10  2]
 [ 1 10  1]]


In [160]:
random_int = np.random.randn(0,12,7)
print(random_int)

[]


In [162]:
normal_dis = np.random.normal(loc=2,scale=15,size=10)
print("the normal distribution is :\n",normal_dis)

the normal distribution is :
 [ 41.76134567  -1.1213798    5.76950923  -1.47906911  -9.81180122
 -19.97635857 -19.25987224 -17.20659303  16.92246728 -17.24581222]


In [220]:
A = np.array([1,2,3,4])
shuffled_array = np.random.shuffle(A)
print(shuffled_array)

None


In [218]:
A = np.array([1,2,3,4])
permutted_array = np.random.permutation(A)
print(permutted_array)

[2 1 3 4]


In [222]:
arr = np.random.choice([3,4,5,6,7,8])
print(arr)

6


In [224]:
arr = np.random.choice([3,4,5,6,7,8],size=(3,2))
print(arr)

[[6 7]
 [3 5]
 [7 4]]


In [ ]:
arr = np.array([3,4,5,6,7,8])
sample = np.random.choice(arr,)

In [37]:
arr = np.random.choice([3,4,5,6,7,8],p = [0.2,0.1,0.2,0.1,0.3,0.1],size=(2,2))
print(arr)


[[7 8]
 [3 5]]
