# Lecture 2: Numpy

## 1. Reshaping and Manipulating Arrays

### 1. Reshape

Reshaping changes the shape of an array without changing its data. The total number of elements must remain the same.


In [1]:
import numpy as np
# Create a 1D array
arr = np.arange(1, 10)  # [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Reshape to a 3x3 array
reshaped_arr = arr.reshape(3, 3)
print("Reshaped Array:\n", reshaped_arr)

Reshaped Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


##### Reshape with -1 (Automatic Dimension Calculation)

You can use -1 to automatically calculate the size of one dimension.

In [2]:
# Reshape to 3 rows, automatically calculate columns
reshaped_arr = arr.reshape(3, -1)
print("Reshaped Array with -1:\n", reshaped_arr)

Reshaped Array with -1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


<h3><span style="color: brown">Practice Question:</span></h3>
<span style="color: green">
Reshape the following array into a <b>2x4</b> array:
</span>

```python
arr = np.arange(1, 9)

In [8]:
arr = np.arange(1,9)
print(arr)
a = arr.reshape(1,-1)
a

[1 2 3 4 5 6 7 8]


array([[1, 2, 3, 4, 5, 6, 7, 8]])

### 2. Transpose (arr.T)

Transposing swaps the rows and columns of a 2D array.

In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])


---
<h3><span style="color: brown">Practice Question:</span></h3>
<span style="color: green">
Transpose the following array:
</span>

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

### 3. Flatten

Flattening converts a multidimensional array into a 1D array.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Flattened array:", arr.flatten())

### 4. Concatenation 

Concatenation combines arrays along a specified axis.

##### a. np.concatenate()

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# Concatenate along rows
result = np.concatenate((a, b), axis=0)
print("Concatenated along rows:\n", result)

In [26]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5], [6]])

# Concatenate along columns
result = np.concatenate((a, b), axis=1)
print("Concatenated along columns:\n", result)

Concatenated along columns:
 [[1 2 5]
 [3 4 6]]


##### b. np.vstack()

Stacks arrays vertically (along rows).

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vertical stacking
result = np.vstack((a, b))
print("Vertical Stack:\n", result)

<h3><span style="color: brown">Practice Question:</span></h3>
<span style="color: green">
Concatenate the following arrays <b>vertically</b>:
</span>

```python
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [15]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c =np.vstack((a,b))
# d = np.hstack((a,b))
c

array([[1, 2],
       [3, 4],
       [5, 6]])

##### c. np.hstack()

Stacks arrays horizontally (along columns).

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Horizontal stacking
result = np.hstack((a, b))
print("Horizontal Stack:", result)

Horizontal Stack: [1 2 3 4 5 6]


<h3><span style="color: brown">Practice Question:</span></h3>
<span style="color: green">
Concatenate the following arrays <b>horizontally</b>:
</span>

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.hstack((a, b))
print("Horizontal Stack:", result)

Horizontal Stack: [1 2 3 4 5 6]


## 2. Linear Algebra

### 1. Dot Product (`np.dot()`)

The dot product of two arrays is the sum of the products of their corresponding elements.




### **Dot Product Formula**
The **dot product** of two vectors **A** and **B** is given by:

$A \cdot B = \sum_{i=1}^{n} A_i B_i$

where:
- \( A \) and \( B \) are vectors of size \( n \),
- \( A_i \) and \( B_i \) are the corresponding elements of the vectors.




In [28]:
#Dot Product of Matrices
# Create two matrices
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Compute the dot product
dot_product = np.dot(A, B)
print("Dot Product of Matrices:\n", dot_product)

Dot Product of Matrices:
 32


<h3><span style="color: brown">Practice Question:</span></h3>
<span style="color: green">
Compute the <b>dot product</b> of the following Matrix:
</span>

```python
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [17]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

dot_product = np.dot(A, B)
print("Dot Product of Matrices:\n", dot_product)

Dot Product of Matrices:
 [[19 22]
 [43 50]]


#### 2. Matrix Multiplication (@ or np.matmul())

Matrix multiplication is a fundamental operation in linear algebra. NumPy provides two ways to perform matrix multiplication:

The @ operator (Python 3.5+).

The np.matmul() function.

In [23]:
# Matrix Multiplication Using @
# Create two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication using @
result = A @ B
print("Matrix Multiplication (using @):\n", result)

Matrix Multiplication (using @):
 [[19 22]
 [43 50]]


In [18]:
# Matrix multiplication using np.matmul()
result = np.matmul(A, B)
print("Matrix Multiplication (using np.matmul()):\n", result)

Matrix Multiplication (using np.matmul()):
 [[19 22]
 [43 50]]


<h3><span style="color: brown">Practice Question:</span></h3>
<span style="color: green">
Perform <b>matrix multiplication</b> on the following matrices:
</span>

```python
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [19]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.matmul(A, B)
print("Matrix Multiplication (using np.matmul()):\n", result)

Matrix Multiplication (using np.matmul()):
 [[19 22]
 [43 50]]


#### 3. Inverse of a Matrix (np.linalg.inv())

The inverse of a matrix is a matrix that, when multiplied by the original matrix, gives the identity matrix.

$A \cdot A^{-1} = I$

In [20]:
# Create a square matrix
A = np.array([[1, 2], [3, 4]])

# Compute the inverse
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)



Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


<h3><span style="color: brown">Practice Question:</span></h3>
<span style="color: green">
Compute the <b>inverse</b> of the following matrix:
</span>

```python
A = np.array([[2, 1], [1, 2]])

In [22]:
A = np.array([[2, 1], [1, 2]])
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

Inverse of A:
 [[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]


#### 4. Determinant of a Matrix (np.linalg.det())

The determinant of a matrix is a scalar value that provides important information about the matrix (e.g., whether it is invertible).

In [23]:
# Create a square matrix
A = np.array([[1, 2], [3, 4]])

# Compute the determinant
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: -2.0000000000000004


#### 5. Eigenvalues and Eigenvectors (np.linalg.eig())

Eigenvalues and eigenvectors are important concepts in linear algebra. They are used in many applications, such as principal component analysis (PCA) and solving differential equations.

In [27]:
# Create a square matrix
A = np.array([[4, 1], [2, 3]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


<h3><span style="color: brown">Practice Question:</span></h3>
<span style="color: green">
Compute the <b>eigenvalues and eigenvectors</b> of the following matrix:
</span>

```python
A = np.array([[6, 1], [1, 4]])

In [28]:
A = np.array([[6, 1], [1, 4]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [6.41421356 3.58578644]
Eigenvectors:
 [[ 0.92387953 -0.38268343]
 [ 0.38268343  0.92387953]]


### **Solving Linear Equations with NumPy**
The `np.linalg.solve(A, B)` function solves the **linear system of equations**:
\[
AX = B
\]
where:
- \( A \) is a square matrix (**coefficient matrix**),
- \( X \) is the **unknown variable vector**,
- \( B \) is the **constant vector**.

**Formula:**

$X = A^{-1} B$


<h3><span style="color: brown">Practice Question:</span></h3>
<span style="color: green"></span>

Solve the **linear system of equations** of the following matrix:


```python

A = np.array([[2, 3], 
              [1, 4]])
              
B = np.array([5, 6])


In [31]:
A = np.array([[2, 3], 
              [1, 4]])
A_inv = np.linalg.inv(A)        
B = np.array([5, 6])
X = np.dot(A_inv,B)
X

array([0.4, 1.4])

## 3. Generating Random Numbers

NumPy provides functions to generate random numbers from various distributions.

####  Random Integers (np.random.randint())

In [32]:
arr = np.random.randint(15)

print(arr)

5


In [33]:
arr=np.random.randint(50, size=(5))

print(arr)

[26 47  8  3 10]


In [39]:
# Generate random integers between 0 and 10 (exclusive)
random_int = np.random.randint(0, 10, size=(1, 4,4)) #Dimension,Row,Column
print("Random integers:\n", random_int)

Random integers:
 [[[0 0 3 7]
  [3 3 6 1]
  [3 1 8 0]
  [6 4 4 4]]]


##### a. Uniform Distribution (np.random.rand())

In [10]:
arr = np.random.rand()

print(arr)

0.5831858133342109


In [41]:
# Generate an array of random numbers (shape: 2x3)
random_arr = np.random.rand(2, 3)
print("Random numbers from uniform distribution:\n", random_arr)

Random numbers from uniform distribution:
 [[0.5323607  0.67590652 0.01314992]
 [0.62934867 0.00657234 0.03743596]]


In [48]:
# Uniform distribution
uniform_numbers = np.random.uniform(low=4, high=8, size=7)
print("Uniform distribution:", uniform_numbers)


Uniform distribution: [5.0072153  6.90889816 6.83350464 5.47964868 5.60283613 7.08070391
 6.57831973]


#### b. Standard Normal Distribution (np.random.randn())

Generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).

In [37]:
# Generate an array of random numbers (shape: 2x3)
random_arr = np.random.randn(2,3)
print("Random numbers from standard normal distribution:\n", random_arr)

Random numbers from standard normal distribution:
 [[ 0.50304154  0.78696957 -1.66936135]
 [ 0.82980434  0.17692592  1.11503677]]


In [38]:
# Normal distribution
normal_numbers = np.random.normal(loc=5, scale=15, size=10)
print("Normal distribution:", normal_numbers)

Normal distribution: [-13.55884718 -14.97904738  -5.6197775    3.17532418 -19.20530221
  -9.69141067  33.80585201  -0.20102373  19.00942645  11.09699001]


#### 3. Shuffling and Sampling

#### a. Shuffling (np.random.shuffle())

Shuffles the elements of an array in place.

In [79]:
arr = np.array([1, 2, 3, 4, 5])

# Shuffle the array
arr1 = np.random.shuffle(arr)
print("Unshuffled array:", arr)
print("Shuffled array:", arr1)


Unshuffled array: [2 1 3 5 4]
Shuffled array: None


In [53]:
# Generate a permutation of the array
permuted_arr = np.random.permutation(arr)

print("Original array:", arr)
print("Permuted array:", permuted_arr)

Original array: [5 1 2 3 4]
Permuted array: [3 5 2 4 1]


#### b. Sampling (np.random.choice())
Randomly samples elements from an array.

In [42]:
arr = np.random.choice([3, 5, 7, 9])

print(arr)

9


In [43]:
arr = np.random.choice([3, 5, 7, 9], size=(3, 5))

print(arr)

[[5 7 5 9 7]
 [7 9 3 9 3]
 [9 5 5 5 3]]


In [37]:
arr = np.array([10, 20, 30, 40, 50])

# Sample 3 elements without replacement
sample = np.random.choice(arr, size=2, replace=False)
print("Sampled elements:", sample)

Sampled elements: [20 40]


In [36]:
arr = np.random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(arr)

[[3 7 7 5 3]
 [7 5 5 7 5]
 [7 7 3 3 7]]


Exercises
Generate a 3x3 array of random numbers from a uniform distribution.

Generate a 1D array of 5 random numbers from a standard normal distribution.

Generate a 2x2 array of random integers between 10 and 20 (inclusive).

Shuffle the following array:

python
Copy
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
Randomly sample 3 elements from the following array without replacement:

python
Copy
arr = np.array([10, 20, 30, 40, 50])

## 4. File I/O with NumPy

#### 1. Saving Arrays

NumPy provides functions to save arrays to disk in binary or text format.


### a. Saving a Single Array (np.save())
 Saves a single array to a .npy file.

In [80]:
# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Save the array to a file
np.save('my_array.npy', arr)
print("Array saved to 'my_array.npy'")

Array saved to 'my_array.npy'


#### b. Saving Multiple Arrays (np.savez())
Saves multiple arrays to a .npz file (a compressed archive).

In [81]:
# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Save the arrays to a file
np.savez('my_arrays.npz', array1=arr1, array2=arr2)
print("Arrays saved to 'my_arrays.npz'")

Arrays saved to 'my_arrays.npz'


#### 2. Loading Arrays

#### a. Loading a Single Array (np.load())
Loads an array from a .npy or .npz file

In [83]:
# Load the array from the file
loaded_arr = np.load('my_array.npy')
print("Loaded array:", loaded_arr)

Loaded array: [1 2 3 4 5]


### 3. Working with Text Files

NumPy provides functions to read and write arrays to text files.

#### a. Saving Arrays to Text Files (np.savetxt())
Saves an array to a text file.

In [84]:
# Create an array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Save the array to a text file
np.savetxt('my_array.txt', arr, fmt='%d', delimiter=' ')
print("Array saved to 'my_array.txt'")

Array saved to 'my_array.txt'


#### b. Loading Arrays from Text Files (np.loadtxt())
Loads an array from a text file.

In [85]:
# Load the array from the text file
loaded_arr = np.loadtxt('my_array.txt')
print("Loaded array from text file:\n", loaded_arr)

Loaded array from text file:
 [[1. 2. 3.]
 [4. 5. 6.]]


## Exercises
### Save the following array to a .npy file:

```python
Save the following arrays to a .npzfile:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
Load the arrays from the .npz file and print them.

Save the following array to a text file with comma-separated values:
arr = np.array([[1, 2, 3], [4, 5, 6]])
Load the array from the text file and print it.

## 5. Image Processing with NumPy

#### Install Required Libraries

pip install pillow

#### 1. Loading and Displaying Images

We'll use the **Pillow (PIL)** library to load, display, and save images.

In [2]:
import numpy as np
from PIL import Image

# Load an image using PIL
image_path = r"C:\Users\1212a\OneDrive\Desktop\Ai 2.0\Numpy\3.jpg"  # Replace with your image path
#image_path = r"E:\DSA Python\elonn_afd24c6793.jpeg" 
image = Image.open(image_path)

# Convert the image to a NumPy array
image_array = np.array(image)

# Display the image using PIL
image.show(title="Original Image")

# Print image shape and data type
print("Image shape:", image_array.shape)  # (height, width, channels)
print("Image data type:", image_array.dtype)

Image shape: (1120, 1120, 3)
Image data type: uint8


### 2. Manipulating Images

#### a. Grayscale Conversion
Convert an RGB image to grayscale by averaging the color channels.

In [3]:
# Convert to grayscale by averaging the RGB channels
grayscale_image = np.mean(image_array, axis=2)

# Convert the NumPy array back to a PIL image
grayscale_image_pil = Image.fromarray(grayscale_image)

# Display the grayscale image
grayscale_image_pil.show(title="Grayscale Image")

#### b. Cropping an Image
Extract a region of interest (ROI) from the image.

In [102]:
# Define the crop region (y1:y2, x1:x2)
cropped_image = image_array[800:2100, 700:1800, :]

# Convert the NumPy array back to a PIL image
cropped_image_pil = Image.fromarray(cropped_image)

# Display the cropped image
cropped_image_pil.show(title="Cropped Image")

#### c. Resizing an Image
Resize an image using NumPy and PIL.

In [51]:
# Resize the image to 200x200 pixels
resized_image = image.resize((400, 400))
resized_array = np.array(resized_image)

# Display the resized image
resized_image.show(title="Resized Image")

#### d. Adjusting Brightness
Increase or decrease the brightness of an image.

In [53]:
# Increase brightness by adding a constant value
brightness_increased = np.clip(image_array + 30, 0, 255).astype(np.uint8)

# Decrease brightness by subtracting a constant value
brightness_decreased = np.clip(image_array - 30, 0, 255).astype(np.uint8)

# Convert the NumPy arrays back to PIL images
brightness_increased_pil = Image.fromarray(brightness_increased)
brightness_decreased_pil = Image.fromarray(brightness_decreased)

# Display the results
brightness_increased_pil.show(title="Brightness Increased")
brightness_decreased_pil.show(title="Brightness Decreased")

#### e. Adjusting Contrast

In [105]:
# Increase contrast
contrast_increased = np.clip(image_array * 1.5, 0, 255).astype(np.uint8)
Image.fromarray(contrast_increased).show()

# Decrease contrast
contrast_decreased = np.clip(image_array * 0.5, 0, 255).astype(np.uint8)
Image.fromarray(contrast_decreased).show()

#### f. Applying Filters
Apply simple filters like blurring or edge detection.

In [ ]:
from scipy.ndimage import convolve 

# Generate Gaussian noise
mean = 0
std = 25  # Adjust the standard deviation for noise intensity
noise = np.random.normal(mean, std, image_array.shape)

# Add noise to the image and clip values to the valid range [0, 255]
noisy_image_array = np.clip(image_array + noise, 0, 255).astype(np.uint8)

# Convert back to PIL image
noisy_image = Image.fromarray(noisy_image_array)

# Display the noisy image
noisy_image.show(title="Noisy Image")



#### g. Rotating image

In [108]:
from scipy.ndimage import rotate

# Rotate the image by 45 degrees
rotated_image = rotate(image_array, angle=45, reshape=True)
Image.fromarray(rotated_image.astype(np.uint8)).show()

#### h. Flip image

In [110]:
# Flip horizontally
flipped_horizontal = np.flip(image_array, axis=0)
Image.fromarray(flipped_horizontal).show()


#### 3. Saving Images
Save the processed image to a file.

In [112]:
# Convert the NumPy array back to a PIL image
# processed_image = Image.fromarray(noisy_image)

# Save the image
output_path = r'blurrred_image.png'
noisy_image.save(output_path)
print(f"Image saved to {output_path}")

Image saved to blurrred_image.png


<h3><span style="color: brown">Practice Question:</span></h3>
<span style="color: green">



Load an image and convert it to grayscale.

Crop the image to a specific region and display it.

Resize the image to 300x300 pixels and save it.

Increase the brightness,contrast of the image by 30 and display the result.

Apply a simple blur filter to the image and save the result.</span>

In [113]:
# Load an image using PIL# Replace with your image path
image_path = r"C:\Users\1212a\OneDrive\Desktop\Ai 2.0\Numpy\2.jpg"
image = Image.open(image_path)

# Convert the image to a NumPy array
image_array = np.array(image)


grayscale_image = np.mean(image_array, axis=2)



Image shape: (4096, 3280, 3)
Image data type: uint8


In [118]:
# Define the crop region (y1:y2, x1:x2)
cropped_image = image_array[800:2300, 800:2200, :]

cropped_image_pil = Image.fromarray(cropped_image)

# Display the cropped image
cropped_image_pil.show(title="Cropped Image")

In [119]:
# Resize the image to 300x300 pixels
resized_image = image.resize((300, 300))
resized_array = np.array(resized_image)

# Display the resized image
resized_image.show(title="Resized Image")

output_path = r'resized_image.png'
resized_image.save(output_path)
print(f"Image saved to {output_path}")

Image saved to resized_image.png


In [120]:

brightness_increased = np.clip(image_array + 30, 0, 255).astype(np.uint8)

# Convert the NumPy arrays back to PIL images
brightness_increased_pil = Image.fromarray(brightness_increased)

# Display the results
brightness_increased_pil.show(title="Brightness Increased")


In [122]:
# Increase contrast
contrast_increased = np.clip(image_array * 30, 0, 255).astype(np.uint8)
contrast_increased_pil = Image.fromarray(contrast_increased)
contrast_increased_pil.show(title="Contrast image")

In [123]:
noise = np.random.normal(1, 20, image_array.shape)

# Add noise to the image and clip values to the valid range [0, 255]
blurred_image_array = np.clip(image_array + noise, 0, 255).astype(np.uint8)

# Convert back to PIL image
blurred_image = Image.fromarray(blurred_image_array)

# Display the noisy image
blurred_image.show(title="Blurred Image")

# Save the image
output_path = r'blurrred2_image.png'
blurred_image.save(output_path)
print(f"Image saved to {output_path}")

Image saved to blurrred2_image.png
