In [1]:
import numpy as np  
list1=[[1,2,3,4,5]]
arr=np.array(list1)
print(arr)


[[1 2 3 4 5]]


In [3]:
import numpy as np  # type: ignore
arr=np.array([1,2,3,4,5,6])
print(arr)
type(arr)

[1 2 3 4 5 6]


numpy.ndarray

In [4]:
zero_arr=np.zeros((3,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
ones_arr=np.ones((4,4))
print(ones_arr)
ones_arr.ndim

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


2

In [7]:
ran_arr=np.arange(0,10,1)
print(ran_arr)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
ran_arra=np.arange(5,16)
print(ran_arra)

[ 5  6  7  8  9 10 11 12 13 14 15]


In [11]:
a=np.full((3,3),9)
a

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [27]:
b=np.full((5,3),7)
b

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [12]:
lins_arr = np.linspace(0,1,9)
print(lins_arr)
lins_arr.ndim

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


1

In [55]:
lins_arr=np.linspace(100,1000,5)
print(lins_arr)
lins_arr.ndim

[ 100.  325.  550.  775. 1000.]


1

In [13]:
iden_arr = np.eye(4)
print(iden_arr)
iden_arr.ndim

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


2

In [14]:
ran_arr = np.random.rand(2,3)
print(ran_arr)

[[0.96621148 0.06166532 0.34121146]
 [0.67759993 0.05493095 0.17391928]]


In [15]:
ran_arran = np.random.rand(4,4)
print(ran_arran)
ran_arran.ndim

[[0.88996104 0.53169332 0.51558196 0.3595039 ]
 [0.53455806 0.84109528 0.43203584 0.83608065]
 [0.63304924 0.73871024 0.47377852 0.94193663]
 [0.07612554 0.62647438 0.46914774 0.0733239 ]]


2

In [42]:
ran_arran.shape

(4, 4)

In [43]:
ran_arr.shape

(2, 3)

In [50]:
arrr=np.array([[1,3,5],
               [3,5,8],
                [3,5,8]])
print(arrr.shape)
print(arrr.dtype)
print(arrr.size)
print(arrr.ndim)

(3, 3)
int64
9
2


In [52]:
arrr1=np.array([[1,0,5],
               [8,5,8],
                [1,7,8]])
print("Shape of array :",arrr1.shape)
print("DataType of array :",arrr1.dtype)
print("Size of array :",arrr1.size)
print("Dimension of array :",arrr1.ndim)

Shape of array : (3, 3)
DataType of array : int64
Size of array : 9
Dimension of array : 2


In [69]:
a = np.array([[2,5,8,8],[3,6,6,7]])
b = np.array([[9,8,3,8],[3,6,7,8]])
print(a+b)

print(a-b)

print(a*b)

print(a/b)

print(a%b)

a.ndim

[[11 13 11 16]
 [ 6 12 13 15]]
[[-7 -3  5  0]
 [ 0  0 -1 -1]]
[[18 40 24 64]
 [ 9 36 42 56]]
[[0.22222222 0.625      2.66666667 1.        ]
 [1.         1.         0.85714286 0.875     ]]
[[2 5 2 0]
 [0 0 6 7]]


2

In [71]:
a = np.array([2,5,8,8])
b=54
print(a+b)

[56 59 62 62]


In [77]:
a = np.array([[2,5,8,8],[3,6,6,7]])
# c = np.array([[2],[4]])
c = np.array([4,5,6,6])
print(a+c)


[[ 6 10 14 14]
 [ 7 11 12 13]]


In [86]:
c = np.array([4,5,6,6])
print("Squareroot of array :",np.sqrt(c))
print("Sum of array :",np.sum(c))
print("Square of array :",np.power(c,2))

Squareroot of array : [2.         2.23606798 2.44948974 2.44948974]
Sum of array : 21
Square of array : [16 25 36 36]


In [91]:
y = np.array([1,2,3,4])
y_p = np.array([1.1,2.05,3.11,4.02])
y_sub = np.subtract(y,y_p)
total = np.power(y_sub,2)
print(total)
sum_power=np.sum(total)
print(sum_power)


[0.01   0.0025 0.0121 0.0004]
0.024999999999999956


In [100]:
angles=np.array([0,30,50,70,90])
radians=np.deg2rad(angles)
print(radians)
cos=np.cos(radians)
print(cos)
sin=np.sin(radians)
print(sin)
degree=np.rad2deg(radians)
print(degree)

[0.         0.52359878 0.87266463 1.22173048 1.57079633]
[1.00000000e+00 8.66025404e-01 6.42787610e-01 3.42020143e-01
 6.12323400e-17]
[0.         0.5        0.76604444 0.93969262 1.        ]
[ 0. 30. 50. 70. 90.]


In [107]:
d=np.array([0,1,2,3])
radians=np.deg2rad(d)

print(np.exp(d))
print(np.sqrt(d))
print(np.sin(radians))
print(np.log(d))


[ 1.          2.71828183  7.3890561  20.08553692]
[0.         1.         1.41421356 1.73205081]
[0.         0.01745241 0.0348995  0.05233596]
[      -inf 0.         0.69314718 1.09861229]


C:\Users\dell\AppData\Local\Temp\ipykernel_13016\4283069101.py:7: RuntimeWarning: divide by zero encountered in log
  print(np.log(d))


In [104]:
print(np.sin(d))

[0.         0.84147098 0.90929743 0.14112001]


In [109]:
d=np.array([[0,1,2,3],[5,6,8,9]])
print(np.sum(d))



34


In [ ]:
print("Sum of number with respect to row",np.sum(d,axis=0))
print("Sum of number with respect to column",np.sum(d,axis=1))

NameError: name 'np' is not defined

In [111]:
print(np.sum(d))
print(np.mean(d))
print(np.max(d))
print(np.min(d))

34
4.25
9
0


In [113]:
d=np.array([0,1,2,3])
x=np.copy(d)
x[0] = 42
print(d)
print(x)

[0 1 2 3]
[42  1  2  3]


In [116]:
d=np.array([0,1,2,3])
x=d.view()
x[0] = 42
print(d)
print(x)

[42  1  2  3]
[42  1  2  3]


In [121]:
d=np.array([0,1,2,3,1,3,1,1,5,1])
x=np.where(d==1)
y = np.searchsorted(d,1)
print(x)
print(y)


(array([1, 4, 6, 7, 9]),)
1


In [122]:
d_2 = np.array([[3,2,1],[2,5,6]])
print(np.sort(d_2))

[[1 2 3]
 [2 5 6]]


In [123]:
d=np.array([0,1,2,3,1,3,1,1,5,1])
print(d[0])

0


In [137]:
d_2 = np.array([[3,2,1],[2,5,6],[7,8,9]])
print(d_2[0:3,0])

[3 2 7]


In [167]:
d_3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
d_3[np.zeros== d_3[1:3,1:3]]
d_3



IndexError: boolean index did not match indexed array along axis 0; size of axis is 4 but size of corresponding boolean axis is 2